spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:\\\E:\Workspace\Microservice-Project\spring-microservices-v1\spring-cloud-config-server\git-localconfig-repo
server:
  port: 8888
